---
- hosts: all
  become: yes
  remote_user: minguss
  tasks:
    - name: Remove a list of docker packages
      yum:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: removed

    - name: Install a list of packages
      yum:
        name:
          - docker-1.13.1-103.git8633870.el7.centos -y
        state: present

#    - name: Downgrade a list of packages
#      shell: yum downgrade docker-1.13.1-75.git8633870.el7.centos docker-client-1.13.1-75.git8633870.el7.centos docker-common-1.13.1-75.git8633870.el7.centos -y
