---
- hosts: all
  become: yes
  remote_user: minguss
  tasks:
    - name: Upgrade docker specific version using shell
      shell: yum update docker-1.13.1-103.git8633870.el7.centos -y

    - name: Install docker package specific version
      yum:
        name:
          - docker-1.13.1-103.git8633870.el7.centos
        state: present

    - name: Start service docker, if not started
      service:
        name: docker
        state: started
        enabled: yes
